version: '3.8'

services:
  binance-converter-telegram-bot:
    image: emil11078/binance-converter-telegram-bot:latest
    command: ./binance-converter-telegram-bot
    environment:
      - GRPC_HOST=backend
      - GRPC_PORT=$BINANCE_CONVERTER_BACKEND_GRPC_PORT
      - BINANCE_CONVERTER_BOOT_TOKEN=$BINANCE_CONVERTER_BOOT_TOKEN
    restart: always


networks:
  default:
    name: binance-converter
    external: true