name: Staging

on:
  push:
    branches: [ feature/deploy-config ]

  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          cache: true

      - name: get deps
        run: go mod download

      - name: Run test
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...

  build-image:
    name: 'Build and push docker image'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: emil11078/binance-converter-telegram-bot:latest
          platforms:
            linux/arm/v7

  deploy:
    name: 'Deploy to server'
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir binance-converter
            cd binance-converter
            git clone https://github.com/binance-converter/telegram-bot.git
            cd telegram-bot
            git checkout feature/setting-deploy-to-server
            export BINANCE_CONVERTER_BACKEND_GRPC_PORT=${{ vars.GRPC_PORT }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_HOST=${{ vars.POSTGRES_USER_DB_HOST }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PORT=${{ vars.POSTGRES_USER_DB_PORT }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_USER_NAME=${{ vars.POSTGRES_USER_DB_NAME }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_PASSWORD=${{ secrets.POSTGRES_USER_DB_PASSWORD }}
            export BINANCE_CONVERTER_BACKEND_POSTGRES_USER_DB_NAME=${{ vars.POSTGRES_USER_DB_USER_NAME }}
            docker-compose -f docker-compose.yaml -p binance-converter up -d --remove-orphans
            cd ../../
            rm -r binance-converter